config/routes.rb
Rails.application.routes.draw do
  
  root 'labworks#index'
    get '/labworks/new', to: 'labworks#new', as:'new_labwork'
    get '/labworks/:id', to: 'labworks#show', as: 'labwork'
    post '/labworks', to: 'labworks#create'
    get '/labworks/:id/edit' ,to: 'labworks#edit' , as: 'edit_labwork'
    put '/labworks/:id' , to: 'labworks#update'
    patch '/labworks/:id' , to: 'labworks#update'
    delete '/labworks/:id', to: 'labworks#destroy'
  get '/labworks/:id/mark', to: 'labworks#mark', as: 'mark_labwork'
  post '/labworks/:id/mark' , to: 'labworks#grade'
  # resources :labworks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/labwork.rb
class Labwork < ApplicationRecord

    belongs_to :user
    validates :title, presence: true, length: { maximum: 250 }
    validates :description, presence: true, length: { maximum: 500 }
    validates :grade, allow_nil: true, format: { with: /[A-F]/}
    
  end

app/models/user.rb
class User < ApplicationRecord

    has_many :labworks
    validates :first_name, presence: true, length: { maximum: 100 }
    validates :last_name, presence: true, length: { maximum: 100 }
    validates :email, presence: true, length: { maximum: 150 }
    validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  
    def to_s
        
        email

    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/labworks_controller.rb
class LabworksController < ApplicationController

    def index
        
        @labwork = Labwork.all

    end

    def show
        
        @labwork = Labwork.find(params[:id])

    end

    def new
        
        @labwork =Labwork.new

    end

    def create
        
        labwork = Labwork.new(params.require(:labwork).permit(:title,:description))
        labwork.user_id=1

        if labwork.save

            redirect_to root_path

        else

            redirect_to root_path
            flash[:DANGER] = "Labwork was not created! "

        end

    end

    def edit
        
        @labwork=Labwork.find(params[:id])

    end

    def update

        @labwork = Labwork.find(params[:id])
        @labwork.update(params.require(:labwork).permit(:title,:description))
        redirect_to root_url

    end

    def destroy

        @labwork = Labwork.find(params[:id])
        @labwork.destroy
        redirect_to root_url

    end

    def mark

        @labwork = Labwork.find(params[:id])

    end

    def grade
        
        @labwork = Labwork.find(params[:id])

        if @labwork.update(params.permit(:grade))
        redirect_to root_url

        else
            render :mark
        end

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labworks_helper.rb
module LabworksHelper
end

app/views/layouts/labworks/edit.html.erb
<h1>Updating new labwork </h1>
<%=form_with model: @labwork do |f|  %>
  <%=f.text_field :title %>
  <%=f.text_area :description%>
  <%=f.submit%>
<%end %>

app/views/layouts/labworks/index.html.erb
<h1>Labworks</h1>
<% flash.each do |msg| %>
    <%= msg %>
<% end %>

<h1><%=link_to 'Create labwork', new_labwork_path %></h1>
<%@labworks.each do |l|o %>
    <h2>Title<br>
<%=l.title %></h2>

    <h2>Description</h2>
    <%=l.description %>
    <h2>Grade<br>
    <%=l.grade%></h2>
    <h2>Autor's email: <%=l.user%></h2>
    <%=link_to 'Show labwork', labwork_path(l) %>
    <%=link_to 'Grade labwork', mark_labwork_path(l) %>
    <%=link_to 'Edit labwork', edit_labwork_path(l) %>
    <%=link_to 'Delete labwork', labwork_path(l), method: :delete, data: {confirm: 'Are you sure?'} %>

<%end %>

app/views/layouts/labworks/mark.html.erb
<h1>Grading labwork</h1>
<%=form_with url: mark_labwork_path(@labwork) do |f|  %>
    <%=f.text_field :grade %>
    <%=f.submit%>
<%end %>

app/views/layouts/labworks/new.html.erb
<h1>Creating new labwork</h1>
<%=form_with model: @labwork do |f|  %>

    <h2>Title</h2>

<%=f.text_field :title %>

    <h2>Description</h2>
    
<%=f.text_area :description%>
<%=f.submit%>
<%end %>

app/views/layouts/labworks/show.html.erb
<h1><%=@Labwork.id %></h1>
<h1><%=@Labwork.title %></h1>
<h1><%=@labwork.description%> </h1>
<h1><%=@Labwork.grade%> </h1>
<%=link_to 'Back', root_url %>

app/views/layouts/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>